### ISSUE TITLE
Voyage monitor Install problems 

### ISSUE THREAD

**Issue by AceMcFly** [IAmPicard/StarTrekTimelinesSpreadsheet#20] opened 2018-03-27 00:29 UTC
Hi!

I cant seem to install the Voyage monitor....

I opened the "Add-AppDevPackage" file with Power Shell and i keep getting a error message "0x0080204"

Help please.....!!!!

Thx

![screenshot 7](https://user-images.githubusercontent.com/33708846/37939970-4b3d4736-3166-11e8-825a-102f72a9234e.png)

**Comment by dewittified** [comment] 2018-03-27 01:07
I am just wondering, did you extract the entire folder? Run As
Administrator?

**Comment by IAmPicard** [comment] 2018-03-27 01:33
What version of Windows are you running? You can check with "winver" from a Run Prompt. I suspect you're running something older than Windows 10 1709 (Fall Creators Update), which is what I targeted when creating the package.

It's generally a good idea to keep Windows up to date; and I've had no problems with 1709 if you're hesitant to upgrade 😄 

Note: this app won't work on Windows 8 or 8.1

**Comment by AceMcFly** [comment] 2018-03-27 06:02
There it is..... I´m running Windows 8.1.... :-(

Well thanks anyways, at least now i can stop trying to get it running....

**Comment by IAmPicard** [comment] 2018-03-27 06:44
FWIW, I believe 8.1 is officially out of support; see if any of these [options](https://www.howtogeek.com/272201/all-the-ways-you-can-still-get-windows-10-for-free/) still work for getting a licensed W10 update for free.

If you really-really must stay on W8.1 for some reason, there’s technically nothing in the app that is 10 specific, but someone needs to build it with 8.1 support (which by default is no longer available in VS2017).

**Comment by IAmPicard** [comment] 2018-04-05 17:12
I'm going to close this issue, as it's not really related to the Electron app, and the cause was identified.

**Closed by IAmPicard** 2018-04-05 17:12 UTC
