### ISSUE TITLE
Voyage calculation in 0.6.9 was great. Very great.

### ISSUE THREAD

**Issue by germanmember** [IAmPicard/StarTrekTimelinesSpreadsheet#53] opened 2018-05-30 07:30 UTC
In the ver. 0.7.1 not.
Please return...

Please...

**Comment by IAmPicard** [comment] 2018-05-30 07:46
Hmm... not sure what you mean. The algorithm didn't change between 0.6.9 and 0.7.1; is there something in particular you're referring to?

**Comment by gblnk** [comment] 2018-05-30 08:32
I've also noticed a change in behavior. In the latest version I'm routinely getting primary skills  that are double the secondary.

**Comment by germanmember** [comment] 2018-05-30 11:08
You're fast, man!
The Tool calculate the best crew to use in the voyage.
The silver and gold traits are much higher in ver 0.7.1 than in 0.6.9
The other 4 Traits are too low. 
In STTCM Ver. 0.6.9 it works perfect.

**Comment by IAmPicard** [comment] 2018-05-30 16:43
I double checked and there were no changes at all to the voyages since 0.6.9. And in fact, the crew selection algorithm wasn't touched since 0.6.7.

Could it be a weird coincidence with the skills / traits being chosen lately skewing the selection (RNG)?

**Comment by gblnk** [comment] 2018-05-30 19:01
I'm willing to believe you that what I'm seeing is just coincidental. But I do think it underscores a problem with the algorithm. I've had a couple recently with a 11-12k primary, a 5-6k secondary and some extremely low tertiary skills. These were estimated well below 8 hours, so that's a lot of points being wasted on the primary. In these cases I've been able to manually select crew with a more even distribution that had roughly the same estimated length.

If I understand correctly, the problem with these extreme skill spreads is that the resulting estimates are increasingly unreliable.

**Comment by IAmPicard** [comment] 2018-05-30 19:06
@ChewableCPP has more insight into the implementation of the algorithm

**Comment by gblnk** [comment] 2018-05-30 19:14
I've been using his voyage estimator to double check the crew recommendations lately, and the last few resulted in dire warnings there, which is why I've brought it up.

**Comment by germanmember** [comment] 2018-05-30 20:19
![voy calc 7](https://user-images.githubusercontent.com/39757459/40744994-8ce7e5f6-6456-11e8-8952-0ce6abc4d8f8.jpg)
a calculation

...

![got bot](https://user-images.githubusercontent.com/39757459/40745031-a697c6ec-6456-11e8-9cb2-06a5cadb1ed4.jpg)
Estimate OK

...

![on voyage](https://user-images.githubusercontent.com/39757459/40745073-bdba39b8-6456-11e8-9749-093b0145de99.png)
Here is what i mean. Gold and silver is very high, the others are very low.

...

The calculation time (0.7.1) on search depth 6 is now very short: 0 sec.
On search depth 7: 10-15 sec.

0.6.9
on search depth 6: 10-20 sec.
on search depth 7: 45-90 sec.

**Comment by germanmember** [comment] 2018-05-30 20:33
![on voyage 2](https://user-images.githubusercontent.com/39757459/40745889-072fbeb8-6459-11e8-91d2-ef960efb9b02.png)
Same voyage. I change 3 Positions only.


![got bot 2](https://user-images.githubusercontent.com/39757459/40745924-24e28b0c-6459-11e8-80f5-a07ac2a86246.jpg)
Got Bot says: Great idea.


Calculation in ver 0.6.9 is not the same. sry.

**Comment by germanmember** [comment] 2018-05-30 20:44
The dirrty algorithm says 8.60
strange.
![voy calc dirrty](https://user-images.githubusercontent.com/39757459/40746542-036ce150-645b-11e8-8d0c-ed153be55e78.jpg)

**Comment by IAmPicard** [comment] 2018-05-30 22:44
I pinged @ChewableCPP and maybe he can take a look when he's available. But yes, there were no changes since 0.6.9 to the voyage calculation code.

Here's another thing you can try: download the 0.6.9 release, then make these changes to make it work against the new client version:

Go to the folder where you installed the app, open resources\app\dist\bundle.js in a text editor and replace

`CLIENT_API_VERSION=9` with `CLIENT_API_VERSION=11`
`CLIENT_VERSION=4.0.3` with `CLIENT_VERSION=5.0.0`

This will confirm you'll get the same results (unless I've completely lost my mind and am just not seeing something 😄).

**Comment by ChewableCPP** [comment] 2018-05-31 06:41
I just tried comparing 0.68 and 0.71, and, yeah, something is wrong. 0.71 was 30 mins worse. I'm afraid I'm too tired to investigate tonight, but I would suggest using an older version with the workaround posted above until we figure this out.

Big thanks for spotting this!

**Comment by ChewableCPP** [comment] 2018-05-31 06:50
Also note that the "quick and dirty" algorithm uses different duration estimation code that is less accurate. It may overestimate duration, so watch out. I'd suggest running the numbers through my codepen estimator, but that won't be entirely reliable either because 1. it uses a more accurate estimation algorithm, but 2. it doesn't take actual proficiency rolls into account

https://codepen.io/somnivore/full/Nabyzw/

**Comment by ChewableCPP** [comment] 2018-05-31 07:05
Just tested. The bug is specifically in 0.71. 0.70 seems to work okay.

**Comment by ChewableCPP** [comment] 2018-05-31 07:17
I believe the 0.71 release was built using old native code/binaries. So this is basically a regression. The voyage ranking function simply crashes (probably because it isn't even there). It feels like this release is using a much older version of the voyage code, before I introduced pbert's inspired improvements.

**Comment by IAmPicard** [comment] 2018-05-31 08:31
If you can give it a try and let me know if results are back to normal, I'd appreciate it

**Comment by ChewableCPP** [comment] 2018-05-31 17:16
Thanks for fixing it. Btw, I was wrong as to the cause. There really was a breaking change to a utility, but not the voyage logic itself.

Confirmed working.

**Comment by IAmPicard** [comment] 2018-05-31 21:01
Closing as resolved. Thanks!

**Closed by IAmPicard** 2018-05-31 21:01 UTC
Labels: bug
